pipeline {
    agent any 
    tools {
        terraform 'TerraformPlugins'
    }
    stages {
        stage('git chekout') {
            steps {
                // below command pull file from github and insert in  /var/lib/jenkins/workspace
               git branch: 'master', url: 'https://github.com/barmaiya/Terraform.git'
            }
        }
                
        stage('terraform connect and copy .tf fle to terraform server') {
            steps {
               sshagent(['Terraform_Server']) {
                    sshPublisher(publishers: [sshPublisherDesc(configName: 'Terraform_Server', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '.', remoteDirectorySDF: false, sourceFiles: 'Terraform/*.tf')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                     
                }
            }
        }
        
        stage('terraform init and apply') {
            steps {
                sshagent(['Terraform_Server']) {
                        sh 'ssh -o StrictHostKeyChecking=no  Admin@172.31.41.40  sudo terraform init'
                        sh 'ssh -o StrictHostKeyChecking=no  Admin@172.31.41.40  sudo terraform apply -auto-approve'
                    }              
                       
            }
        }
      

    }
}
