pipeline {
    agent any 
    // tools {
    //     //terraform 'TerraformPlugins'
    // }
    stages {
        stage('git chekout') {
            steps {
                // below command pull file from github and insert in  /var/lib/jenkins/workspace
               git branch: 'master', url: 'https://github.com/barmaiya/Terraform.git'
            }
        }
                
        stage('terraform connect and copy .tf fle to terraform server') {
            steps {
               sshPublisher(publishers: [sshPublisherDesc(configName: 'ansibleserver', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '.', remoteDirectorySDF: false, removePrefix: 'Terraform/', sourceFiles: 'Terraform/*.tf')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
            }
        }
        
        stage('terraform init and apply') {
            steps {
                //terraKey has been added in Jenkins with ec2-user and privateKey
                //note we have to add ec2-user only other wont work as aws machine we login with ec2-user
                //so below ec2-user@172.31.37.74 means like we login in putyy using ec2-user in 172.31.41.40
                sshagent(['ansiblekey1']) {
                        sh 'ssh -o StrictHostKeyChecking=no  ec2-user@172.31.37.74   terraform init'
                        sh 'ssh -o StrictHostKeyChecking=no  ec2-user@172.31.37.74   terraform apply -auto-approve'
                    }              
                       
            }
        }
      

    }
}
