pipeline {
    agent any 
    stages {
        stage('git chekout') {
            steps {
                // below command pull file from github and insert in  /var/lib/jenkins/workspace
               git branch: 'main', credentialsId: 'github', url: 'https://github.com/barmaiya/Terraform.git'
            }
        }
                
        stage('terraform connect and copy .tf fle to terraform server') {
            steps {
               sshagent(['terraformserver']) {
                    sshPublisher(publishers: [sshPublisherDesc(configName: 'terraformserver', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '.', remoteDirectorySDF: false, sourceFiles: 'Terraform/*.tf')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                     
                }
            }
        }
        
        stage('terraform init and apply') {
            steps {
                sshagent(['terraformserver']) {
                        sh 'ssh -o StrictHostKeyChecking=no  ec2-user@172.31.40.57  terraform init'
                        sh 'ssh -o StrictHostKeyChecking=no  ec2-user@172.31.40.57  terraform apply -auto-approve'
                    }              
                       
            }
        }
      

    }
}
