---
- hosts: nodeserver
  tasks:
    - name: Installs  application
      apt: pkg=nginx state=installed update_cache=true
      notify:
        - start nginx

  handlers:
    - name: start nginx
      service: name=nginx state=started