---
- hosts: all
  become: yes
  tasks:
    - name: stop existing container
      shell:  docker container stop web

    - name: remove existing container
      shell:  docker container rm web

    - name: remove existing image
      shell:  docker image rm barmaiya/dockertask 
       
    - name: create container out of docker image
      shell:  docker container run --name web -itd  -p 5000:5000 barmaiya/dockertask

     

  