pipeline {
    agent any 
    stages {
        
        stage('ansible server connect and copy yaml fle to ansible server') {
            steps {
                sshagent(['ansibleserver']) {
                     sshPublisher(publishers: [sshPublisherDesc(configName: 'ansibleserver', transfers: [sshTransfer(cleanRemote: false, excludes: '', execCommand: '', execTimeout: 120000, flatten: false, makeEmptyDirs: false, noDefaultExcludes: false, patternSeparator: '[, ]+', remoteDirectory: '.', remoteDirectorySDF: false, sourceFiles: 'Ansible/*.*')], usePromotionTimestamp: false, useWorkspaceInPromotion: false, verbose: false)])
                     
                }
            }
        }

        stage('Ansible run') {
            steps {
                sshagent(['ansibleserver']) {
                        sh 'ssh -o StrictHostKeyChecking=no  root@172.31.43.10  ansible-playbook nginx.yaml'
                       // sh 'ssh -o StrictHostKeyChecking=no  ec2-user@172.31.40.57  ansible-playbook app_deploy.yml'
                    }              
                       
            }
        }

       
        

    }
}
